### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by sarmel** [Drakkar-Software/OctoBot-Tentacles#20]
Can a tentacle support Triangular Arbitrage strategy or long/short strategy?

**Comment by Herklos** [comment]
Hi sarmel, 

Thank you for your interest on OctoBot project ! 

Currently the project is on development and we have already scheduled to develop an [arbitrage feature](https://github.com/Drakkar-Software/OctoBot/issues/336). You can follow this issue to be kept informed about this feature.

Herklos

**Comment by sarmel** [comment]
Thanks
